name: "get list artifacts"
description: "gets all artifacts for the current repository"
inputs:
  GITHUB_TOKEN:
    description: "github access token for callers repository"
    required: false,
    default: ${{ github.token }}
  repository:
    reqired: false
    default: ${{ github.repository }}
outputs:
  artifacts: # output will be available to future steps
    description: 'list of artifacts'
runs:
  using: 'node12'
  main: 'dist/index.js'
