name: "get artifacts"
description: "gets all artifacts in repository"
author: "Michael Melena"
branding:
  icon: 'list'
  color: 'purple'
inputs:
  GITHUB_TOKEN:
    description: "github access token"
    required: false
    default: ${{ github.token }}
  repository:
    reqired: false
    default: ${{ github.repository }}
outputs:
  artifacts:
    description: 'list of artifacts'
runs:
  using: 'node12'
  main: 'dist/index.js'
